services:
  - type: web
    name: gleicop-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL
